### ISSUE TITLE
Illegal State Exception on withdrawing while balance is 0

### ISSUE THREAD

**Issue by solomon56** [Squawkers13/FeatherEconomy#1]
Caused by: java.lang.IllegalStateException: Attempted to withdraw more than the player had
        at net.pekkit.feathereconomy.api.FeatherAPI.withdrawPlayer(FeatherAPI.java:103) ~[?:?]
        at net.pekkit.feathereconomy.vault.Economy_FeatherEcon.withdrawPlayer(Economy_FeatherEcon.java:260) ~[?:?]
        at net.diecode.KillerMoney.Functions.MoneyLoss.onMoneyReward(MoneyLoss.java:31) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        ... 32 more

**Comment by solomon56** [comment]
title was supposed to read "Multiple plugins throw this error when balance is 0"

**Comment by Squawkers13** [comment]
Interesting. What plugins have caused this?

**Comment by solomon56** [comment]
KillerMoney while killing a villager and ChatControl fining people for swearing
